### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by mikulely** [millyz/SimEDC#1]
Hi~ @millyz   We've run the following cmds with current master codebase:

```
python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T hie --network_setting=250,250  --total_iterations=120 --chunk_size=4 --num_stripes=1024 --capacity_per_disk=12582912  --disks_per_node=1 --mission_time=8760 > mission_1.txt  & # 1 year
python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T hie --network_setting=250,250 --total_iterations=120 --chunk_size=4  --num_stripes=1024 --capacity_per_disk=12582912  --disks_per_node=1 --mission_time=17520 > mission_2.txt & # 2 years
python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T hie --network_setting=250,250 --total_iterations=120 --chunk_size=4  --num_stripes=1024 --capacity_per_disk=12582912  --disks_per_node=1 --mission_time=26280 > mission_3.txt & # 3 years
python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T hie --network_setting=250,250 --total_iterations=120 --chunk_size=4  --num_stripes=1024 --capacity_per_disk=12582912  --disks_per_node=1 --mission_time=35040 > mission_4.txt & # 4 years
python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T hie --network_setting=250,250 --total_iterations=120 --chunk_size=4  --num_stripes=1024 --capacity_per_disk=12582912  --disks_per_node=1 --mission_time=43800 > mission_5.txt & # 5 years
```

```
[root@node4 SimEDC]#
[1]   Exit 1                  python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T hie --network_setting=250,250 --total_iterations=120 --chunk_size=4 --num_stripes=1024 --capacity_per_disk=12582912 --disks_per_node=1 --mission_time=8760 > mission_1.txt
[2]   Done                    python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T hie --network_setting=250,250 --total_iterations=120 --chunk_size=4 --num_stripes=1024 --capacity_per_disk=12582912 --disks_per_node=1 --mission_time=17520 > mission_2.txt
[3]   Done                    python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T hie --network_setting=250,250 --total_iterations=120 --chunk_size=4 --num_stripes=1024 --capacity_per_disk=12582912 --disks_per_node=1 --mission_time=26280 > mission_3.txt
[4]-  Exit 1                  python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T hie --network_setting=250,250 --total_iterations=120 --chunk_size=4 --num_stripes=1024 --capacity_per_disk=12582912 --disks_per_node=1 --mission_time=35040 > mission_4.txt
[5]+  Done                    python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T hie --network_setting=250,250 --total_iterations=120 --chunk_size=4 --num_stripes=1024 --capacity_per_disk=12582912 --disks_per_node=1 --mission_time=43800 > mission_5.txt
```

And we've encountered *ZeroDivisionError: float division by zero* by mission_time = 1/4 years:

```
[root@node4 SimEDC]# Traceback (most recent call last):
  File "simedc.py", line 457, in <module>
    results_list = pool.map(do_it, jobs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "simedc.py", line 457, in <module>
    results_list = pool.map(do_it, jobs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
ZeroDivisionError: float division by zero
```

```
[root@node4 SimEDC]# grep NOMDL mission_*.txt
mission_2.txt:NOMDL (bytes/byte) = 0.000000e+00
mission_3.txt:NOMDL (bytes/byte) = 0.000000e+00
mission_5.txt:NOMDL (bytes/byte) = 0.000000e+00
```
Am I mis-configed? Would you mind to take a look? Thx.

**Comment by millyz** [comment]
Hi, your configuration seems fine.
- I run your first configuration with less iterations and it works correctly. So I fail to reproduce your error now. One thing you can try is to set num_processes as 1 (do not use multiprocessing) to get the exact error message and see where ZeroDivisionError occurs.
- For the configuration 2, 3, 5, NOMDL can be 0 if no data loss. For a highly reliable system, it is not enough to set iteration as 120. You may try to set a larger value (eg, 1000) for the number of iterations.

**Comment by mikulely** [comment]
HI` @millyz  . After changed  *--num_processes=1* and  *--total_iterations=1200* with:

```
python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T hie --num_processes=1 --network_setting=250,250  --total_iterations=1200 --chunk_size=4 --num_stripes=1024 --capacity_per_disk=12582912  --disks_per_node=1 --mission_time=8760 > mission_1.txt  # 1 year
```

there's no error:

```
*************** Result ***************
num_zeroes = 1200
PDL = 0.000000e+00
RE = 0.0%
NOMDL (bytes/byte) = 0.000000e+00
BR = 0.000000e+00
Single-chunk repair ratio = 0.000000
***************************************
```

but the NOMDL is still 0,I'll follow your suggestion to change *total_iterations* to 120000 and give it a try. Thx again!
