### ISSUE TITLE
ZeroDivisionError for disk_per_node simulation

### ISSUE THREAD

**Issue by mikulely** [millyz/SimEDC#2]
Hi~ @millyz  W're trying to evaluate the impacts of disks_per_node for NOMDL by using the following simedc config:

```
### 12 disks_per_node

python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T  hie --num_processes=1  --network_setting=125,125 --total_iterations=120000 --chunk_size=4 --num_stripes=1024 --capacity_per_disk=12582912  --disks_per_node=12 --mission_time=43800 > disk_12.txt # 5 years

### 6 disks_per_node

python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T  hie --num_processes=1  --network_setting=125,125 --total_iterations=120000 --chunk_size=4 --num_stripes=1024 --capacity_per_disk=12582912  --disks_per_node=6 --mission_time=43800 > disk_6.txt # 5 years

### 4 disks_per_node

python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T  hie --num_processes=1  --network_setting=125,125 --total_iterations=120000 --chunk_size=4 --num_stripes=1024 --capacity_per_disk=12582912  --disks_per_node=4 --mission_time=43800  > disk_4.txt # 5 years

### 3 disks_per_node

python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T  hie --num_processes=1  --network_setting=125,125 --total_iterations=120000 --chunk_size=4 --num_stripes=1024 --capacity_per_disk=12582912  --disks_per_node=3 --mission_time=43800 > disk_3.txt # 5 years

### 1 disks_per_node

python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T  hie --num_processes=1  --network_setting=125,125 --total_iterations=120000 --chunk_size=4 --num_stripes=1024 --capacity_per_disk=12582912  --disks_per_node=1 --mission_time=43800 > disk_1.txt # 5 years
```

 I've found that after setting  --num_processes=1，we still can't can the error trace:

```
[root@node4 SimEDC]# python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T  hie --num_processes=1  --network_setting=125,125 --total_iterations=120000 --chunk_size=4 --num_stripes=1024 --capacity_per_disk=12582912  --disks_per_node=3 --mission_time=43800 > disk_3.txt # 5 years

Traceback (most recent call last):
  File "simedc.py", line 457, in <module>
    results_list = pool.map(do_it, jobs)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
ZeroDivisionError: float division by zero
```

I've disable multiprocessing lib by:

```
[root@node4 SimEDC]# git diff
diff --git a/simedc.py b/simedc.py
index 824d701..ab372fe 100755
--- a/simedc.py
+++ b/simedc.py
@@ -430,7 +430,7 @@ if __name__ == "__main__":
             sys.exit(2)
         parser.parse_traces()

-    pool = multiprocessing.Pool(num_processes)
+    #pool = multiprocessing.Pool(num_processes)
     n = num_processes * 1
     if total_iterations % n != 0:
         print "total_iterations should be divided by n!"
@@ -453,8 +453,8 @@ if __name__ == "__main__":

     for idx in xrange(len(jobs)):
         jobs[idx] += params_tuple
-    # results_list = map(do_it, jobs)
-    results_list = pool.map(do_it, jobs)
+    results_list = map(do_it, jobs)
+    #results_list = pool.map(do_it, jobs)
```

then I've got the real error:

```
root@node4 SimEDC]#  python simedc.py -n 12 -k 10 -g 3,3,3,3 -t rs -T  hie --num_processes=1  --network_setting=125,125 --total_iterations=120000 --chunk_size=4 --num_stripes=1024 --capacity_per_disk=12582912  --disks_per_node=3 --mission_time=43800 > disk_3.txt # 5 years
Traceback (most recent call last):
  File "simedc.py", line 456, in <module>
    results_list = map(do_it, jobs)
  File "simedc.py", line 335, in do_it
    return simulation.run_simulation(iter_num)
  File "simedc.py", line 74, in run_simulation
    rst_list.append(self.sim.run_iteration(i))
  File "/root/jiaying/SimEDC/lib/is_simulation.py", line 390, in run_iteration
    (event_time, event_type, subsystem_idx) = self.get_next_event(curr_time)
  File "/root/jiaying/SimEDC/lib/is_simulation.py", line 287, in get_next_event
    self.set_node_repair(next_event_subsystem, next_event_time)
  File "/root/jiaying/SimEDC/lib/is_simulation.py", line 246, in set_node_repair
    node_repair_duration += self.get_disk_repair_duration(disk_idx)
  File "/root/jiaying/SimEDC/lib/is_simulation.py", line 214, in get_disk_repair_duration
    self.total_repair_rate += 3600. / repair_duration
ZeroDivisionError: float division by zero
```

but I'm not familiar with the simedc‘s implementation, would you mind to take a look?  Thx.

**Comment by millyz** [comment]
Hi @mikulely, thanks for your information. I've fixed the bug, which is caused by repairing an empty disk (repair_duration = 0). You can try it again.
